
import java.awt.Image;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VIJAY KRISHAN PANDEY
 */



import javax.swing.*;
public class code extends javax.swing.JFrame {

    /**
     * Creates new form code
     */
    ButtonGroup bg;
    String stringcode;
    public code() throws IOException{
        
        initComponents();
        bg=new ButtonGroup();
        bg.add(practice);
        bg.add(contest);
        stringcode="";
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pic = new javax.swing.JLabel();
        stars = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        country = new javax.swing.JLabel();
        col2 = new javax.swing.JTextField();
        col3 = new javax.swing.JTextField();
        col4 = new javax.swing.JTextField();
        code = new javax.swing.JTextField();
        practice = new javax.swing.JCheckBox();
        contest = new javax.swing.JCheckBox();
        sol = new javax.swing.JButton();
        col1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setResizable(false);

        pic.setToolTipText("");

        stars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stars.setText("Profile Pic");

        user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        user.setText("Enter codechef username");
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        jLabel1.setText("Country:");

        jLabel2.setText("City:");

        jLabel3.setText("Student/Professional");

        jLabel4.setText("Institution:");

        code.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        code.setText("Problem Code");

        practice.setText("Practice");

        contest.setText("Contest");

        sol.setText("View Solution");
        sol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(user, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(stars, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(practice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(col2)
                            .addComponent(col3)
                            .addComponent(col4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addComponent(sol, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addComponent(col1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contest)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stars, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(country, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                            .addComponent(col1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(col2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(col3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(col4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(practice)
                            .addComponent(sol))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contest)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solActionPerformed(java.awt.event.ActionEvent evt) {                                    
        if(contest.isSelected()==true){
            stringcode=JOptionPane.showInputDialog(this,"Enter the contest code");
        }
        if(practice.isSelected()==true){
             getsetgo("");
        }
        else if(contest.isSelected()==true && stringcode.length()!=0){
            String m=stringcode+"/";
            System.out.println("vijay" +" " + m);
            getsetgo(m);
        }
       
    }  
    
  public void getsetgo(String magic){

         String url="https://www.codechef.com/"+magic+"status/"+code.getText()+","+user.getText();
             System.out.println(url);
             System.out.println("reached");
        try
        {
        Document document=Jsoup.connect(url.toString()).get();
        Elements ee=document.getElementsByTag("a");
        String str="View";
        String url22="";
        String y="";
        
        for(Element eeee:ee){
        //    System.out.println(eeee.teh=xt());
            if(eeee.text().equals(str)){
                url22=eeee.attr("href");
                y=url22.substring(url22.lastIndexOf("/")+1,url22.length());
                System.out.println("View"+" "+url22);
            }
        }
       int h=-1;
       Elements soluchan=document.getElementsByTag("tbody");
       Vector<Submissionss> v=new Vector<Submissionss>();
       for(Element solu:soluchan){
           Elements s=solu.children();
           //System.out.println(solu.text());
           for(Element child:s){
               String sub=child.text();
               String c=sub.substring(0,sub.indexOf(" "));
               
               if(dfun(c)==true && sub.contains("View")){
               System.out.println(child.text());
                   Submissionss obj=subfun(sub);
                   v.add(obj);
                   if(c.equals(y)==true)
                   {   h=0;    break;}
                   System.out.println("going");
                  // obj.print();
               }
               if(h==0)
                   break;
               
               
           }
           
       }
       System.out.println("out");
       String url33="https://www.codechef.com/viewplaintext/"+url22.substring(url22.lastIndexOf("/")+1,url22.length());
      // System.out.println(url33);
      // document=Jsoup.connect(url33).get();
       System.out.println("phew");
       //TextBro obj=new TextBro(this,document.select("pre").first().text());
       View obj=new View(this,v);
        }
         catch(Exception e)
        {
            System.out.println("oddibaba");
        }
            
}
boolean dfun(String s){
    for(int i=0;i<s.length();i++){
        if(Character.isDigit(s.charAt(i))==false)
            return false;
    }
    return true;
}
Submissionss subfun(String srr){
    Submissionss obj=new Submissionss();
    int flag=-1;
    obj.id=srr.substring(0,srr.indexOf(" "));
    obj.print();
    srr=srr.substring(0,srr.lastIndexOf(" "));
    obj.language=srr.substring(srr.lastIndexOf("M")+1,srr.length());
     obj.print();
     srr=srr.substring(0,srr.lastIndexOf("M")+1);
     obj.memory=srr.substring(srr.lastIndexOf(" ")+1,srr.length());
      obj.print();
     if((obj.memory).equals("-"))
     {flag=1; obj.flag="1";}
      obj.print();
     srr=srr.substring(0,srr.lastIndexOf(" "));
      obj.print();
     obj.time=srr.substring(srr.lastIndexOf(" ")+1,srr.length());
      obj.print();
     if((obj.time).equals("-") && flag==-1) {
         {flag=1;obj.flag="2";}
     } 
      obj.print();
     
     srr=srr.substring(0,srr.lastIndexOf(" "));
     String temp=srr.substring(srr.lastIndexOf(" ")+1,srr.length());;
      obj.print();
     if(temp.endsWith(user.getText())){
         System.out.println("hi wrong runtime");
         if(((obj.time).equals("0.00")|| (obj.memory).equals("0M")) && flag==-1)
         {
             obj.flag="4";
             flag=1;
         }
         else if(flag==-1)
         {
             obj.flag="3";
             flag=1;
         }
         obj.score="0pts";
          obj.print();
     }
     else{
         obj.flag="5";
         obj.score=temp.substring(1,temp.length()-1);
         flag=1;
     }
      obj.print();
      System.out.println("end");
   return obj; 
}
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
       String str=user.getText();
       String url="https://www.codechef.com/users/";
       url=url+str;
       Document document = null;
        try {
            document = Jsoup.connect(url).get();
        } catch (IOException ex) {
            Logger.getLogger(code.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String reqimg="";
         Elements picc=document.getElementsByTag("header");
         
         int i=0;
         for(Element picccc:picc){
            Elements img=picccc.getElementsByTag("img");
       //     System.out.println(picccc.text()+" "+"sss");
            for(Element ii:img)  {    
                   System.out.println(ii.attr("src"));
                   reqimg=ii.attr("src"); 
            }
    }//GEN-LAST:event_userActionPerformed
/*
    private void solActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_solActionPerformed
  /*      */    Elements im=document.getElementsByClass("rating-star");
        String star="";
        for(Element immm:im){
            star=immm.text().toString();
        }
        if(reqimg.length()==0)
        reqimg="https://s3.amazonaws.com/codechef_shared/sites/all/themes/abessive/images/user_default_thumb.jpg";
        Element con=document.getElementsByClass("user-country-flag").first();
        String conimg=con.attr("src");
        conimg="https://s3.amazonaws.com/codechef_shared"+conimg;
        System.out.println(conimg);
        Elements sta=document.getElementsContainingText("Country");
        String s1="",s2="";
        String col1,col2,col3,col4;
        for(Element staa:sta){
            s1=s2;
            s2=staa.text();
            if(s2.equals("Country:"))
                break;
        }
        col1=s1.substring(s1.indexOf(":")+1,s1.length());
        sta=document.getElementsContainingText("City");
        for(Element staa:sta){
            s1=s2;
            s2=staa.text();
            if(s2.equals("City:"))
                break;
        }
        col2=s1.substring(s1.indexOf(":")+1,s1.length());
        sta=document.getElementsContainingText("Student/Professional");
        for(Element staa:sta){
            s1=s2;
            s2=staa.text();
            if(s2.equals("Student/Professional:"))
                break;
        }
        col3=s1.substring(s1.indexOf(":")+1,s1.length());
        sta=document.getElementsContainingText("Institution");
        for(Element staa:sta){
            s1=s2;
            s2=staa.text();
            if(s2.equals("Institution:"))
                break;
        }
        col4=s1.substring(s1.indexOf(":")+1,s1.length());
         try {
            fun(reqimg,star,conimg,col1,col2,col3,col4);
        } catch (IOException ex) {
            Logger.getLogger(code.class.getName()).log(Level.SEVERE, null, ex);
        }
   
    }
    public void fun(String str,String star,String Country,String cola,String colb,String colc,String cold)throws IOException{
        URL url=new URL(str);
        Image image=ImageIO.read(url);
        pic.setIcon(new ImageIcon(image));
        int l=star.length();
        if(l==1)
        stars.setText("<html><div class=\"rating-star\"><span style=\"background-color:#666666\">&#9733;</span></div>");
        else if(l==2)
        stars.setText("<html><div class=\"rating-star\"><span style=\"background-color:#1E7D22\">&#9733;</span><span style=\"background-color:#1E7D22\">&#9733;</span></div>");
        else if(l==3)
        stars.setText("<html><div class=\"rating-star\"><span style=\"background-color:#3366CC\">&#9733;</span><span style=\"background-color:#3366CC\">&#9733;</span><span style=\"background-color:#3366CC\">&#9733;</span></div>");
        else if(l==4)
        stars.setText("<html><div class=\"rating-star\"><span style=\"background-color:#684273\">&#9733;</span><span style=\"background-color:#684273\">&#9733;</span><span style=\"background-color:#684273\">&#9733;</span><span style=\"background-color:#684273\">&#9733;</span></div>");
        else if(l==5)
        stars.setText("<html><div class=\"rating-star\"><span style=\"background-color:#FFBF00\">&#9733;</span><span style=\"background-color:#FFBF00\">&#9733;</span><span style=\"background-color:#FFBF00\">&#9733;</span><span style=\"background-color:#FFBF00\">&#9733;</span><span style=\"background-color:#FFBF00\">&#9733;</span></div>");
        else if(l==6)
        stars.setText("<html><div class=\"rating-star\"><span style=\"background-color:#FF7F00\">&#9733;</span><span style=\"background-color:#FF7F00\">&#9733;</span><span style=\"background-color:#FF7F00\">&#9733;</span><span style=\"background-color:#FF7F00\">&#9733;</span><span style=\"background-color:#FF7F00\">&#9733;</span><span style=\"background-color:#FF7F00\">&#9733;</span></div>");
        else if(l==7)
        stars.setText("<html> <div class=\"rating-star\"><span style=\"background-color:#D0011B\">&#9733;</span><span style=\"background-color:#D0011B\">&#9733;</span><span style=\"background-color:#D0011B\">&#9733;</span><span style=\"background-color:#D0011B\">&#9733;</span><span style=\"background-color:#D0011B\">&#9733;</span><span style=\"background-color:#D0011B\">&#9733;</span><span style=\"background-color:#D0011B\">&#9733;</span></div>");
        else
        stars.setText("Unrated");
        url=new URL(Country);
        image=ImageIO.read(url);
        country.setIcon(new ImageIcon(image));
        col1.setText(cola);
        col2.setText(colb);
        col3.setText(colc);
        col4.setText(cold);
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])throws MalformedURLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(code.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    new code().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(code.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField code;
    private javax.swing.JTextField col1;
    private javax.swing.JTextField col2;
    private javax.swing.JTextField col3;
    private javax.swing.JTextField col4;
    private javax.swing.JCheckBox contest;
    private javax.swing.JLabel country;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel pic;
    private javax.swing.JCheckBox practice;
    private javax.swing.JButton sol;
    private javax.swing.JLabel stars;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
